<a href="https://colab.research.google.com/github/sriman21/CODSOFT-TASK03-Recommendation-System/blob/main/Untitled5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [24]:
movies_data = pd.read_csv('movies.csv')

In [25]:
movies_data.head()

,movieId,title,genres,Column1,Column2,Column3,Column4,Column5,Column6,Column7,...,Column16372,Column16373,Column16374,Column16375,Column16376,Column16377,Column16378,Column16379,Column16380,Column16381
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Jumanji (1995),Adventure|Children|Fantasy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Grumpier Old Men (1995),Comedy|Romance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Father of the Bride Part II (1995),Comedy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
movies_data.shape

(181, 16384)

In [28]:
movies_data.columns = movies_data.columns.str.strip()

In [29]:
if 'genres' in movies_data.columns:
    movies_data['genres'] = movies_data['genres'].fillna('')
else:
    raise KeyError("The 'genres' column is not found in the dataset.")

In [30]:
vectorizer = TfidfVectorizer(token_pattern=r'(?u)\b\w+\b')  # Adjust token pattern to handle '|' separator
feature_vectors = vectorizer.fit_transform(movies_data['genres'])

In [31]:
similarity = cosine_similarity(feature_vectors)

In [33]:
similarity

array([[1.        , 0.75076087, 0.16551399, ..., 0.16551399, 0.30871925,
        0.        ],
       [0.75076087, 1.        , 0.        , ..., 0.        , 0.4112085 ,
        0.        ],
       [0.16551399, 0.        , 1.        , ..., 1.        , 0.        ,
        0.65289018],
       ...,
       [0.16551399, 0.        , 1.        , ..., 1.        , 0.        ,
        0.65289018],
       [0.30871925, 0.4112085 , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.65289018, ..., 0.65289018, 0.        ,
        1.        ]])

In [37]:
def recommend_movies(movie_name, num_recommendations=10):
    list_of_all_titles = movies_data['title'].tolist()
    find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
    if not find_close_match:
        return f"No close matches found for '{movie_name}'"
    close_match = find_close_match[0]
    index_of_the_movie = movies_data[movies_data.title == close_match].index[0]
    similarity_score = list(enumerate(similarity[index_of_the_movie]))
    sorted_similar_movies = sorted(similarity_score, key=lambda x: x[1], reverse=True)
    print(f"Movies suggested for you (based on '{close_match}'):\n")
    i = 1
    for movie in sorted_similar_movies[1:num_recommendations+1]:  # Skipping the first one as it's the movie itself
        index = movie[0]
        title_from_index = movies_data.iloc[index]['title']
        print(f"{i}. {title_from_index}")
        i += 1

In [44]:
user_movie = input('Enter your favorite movie name: ')
recommend_movies(user_movie, num_recommendations=10)

Enter your favorite movie name: Toy Story
Movies suggested for you (based on 'Toy Story (1995)'):

1. Balto (1995)
2. Kids of the Round Table (1995)
3. Jumanji (1995)
4. Indian in the Cupboard, The (1995)
5. NeverEnding Story III, The (1994)
6. Mortal Kombat (1995)
7. Tom and Huck (1995)
8. Amazing Panda Adventure, The (1995)
9. Casper (1995)
10. Pocahontas (1995)